In [1]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
voc_size=10000
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1040, 7246, 9927, 9496],
 [1040, 7246, 9927, 4920],
 [1040, 8795, 9927, 7263],
 [1312, 5809, 9069, 3380, 3070],
 [1312, 5809, 9069, 3380, 3575],
 [9846, 1040, 1011, 9927, 5459],
 [456, 8856, 2112, 3380]]

In [5]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1040 7246 9927 9496]
 [   0    0    0    0 1040 7246 9927 4920]
 [   0    0    0    0 1040 8795 9927 7263]
 [   0    0    0 1312 5809 9069 3380 3070]
 [   0    0    0 1312 5809 9069 3380 3575]
 [   0    0    0 9846 1040 1011 9927 5459]
 [   0    0    0    0  456 8856 2112 3380]]


In [6]:
dim=10

In [7]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
